---
  - name: Check GCP repo file exist
    stat:
      path: /etc/yum.repos.d/google-cloud.repo
    register: gcp_repo_exist
    become: yes

  - ansible.builtin.replace:
      path: /etc/yum.repos.d/google-cloud.repo
      regexp: 'repo_gpgcheck=1'
      replace: 'repo_gpgcheck=0'
    when: gcp_repo_exist.stat.exists == True
    become: yes

  - name: download nodejs rpm
    shell: 'yum install https://rpm.nodesource.com/pub_16.x/nodistro/repo/nodesource-release-nodistro-1.noarch.rpm -y'
    become: yes
    ignore_errors: yes

  - name: install nodejs from nodesource
    shell: 'yum install nodejs -y --setopt=nodesource-nodejs.module_hotfixes=1'
    become: yes

  - name: install build essentials for native modules
    yum:
      name: gcc-c++
      state: present
    become: yes
